### ISSUE TITLE
Error on run - module 'wx' has no attribute 'ItemAttr'

### ISSUE THREAD

**Issue by kevin201** [timinaust/metamorphose2#4]
Versions:
Python 3.8.10
python3-wxgtk4.0/focal,now 4.0.7+dfsg-2build1 amd64 [installed]
python3-pil/focal-updates,focal-security,now 7.0.0-4ubuntu0.5 amd64 [installed]

Installed as per instructions:

$ git clone -b Python3_WXPython4 https://github.com/timinaust/metamorphose2.git
Cloning into 'metamorphose2'...
remote: Enumerating objects: 1825, done.
remote: Counting objects: 100% (280/280), done.
remote: Compressing objects: 100% (206/206), done.
remote: Total 1825 (delta 67), reused 218 (delta 58), pack-reused 1545
Receiving objects: 100% (1825/1825), 3.02 MiB | 2.47 MiB/s, done.
Resolving deltas: 100% (1018/1018), done.

$ cd metamorphose2/

$ git submodule update --init
Submodule 'exif-py' (https://github.com/ianare/exif-py.git) registered for path 'src/exif'
Cloning into '/home/kevin/metamorphose2/src/exif'...
Submodule path 'src/exif': checked out '1df7e113b924724f56ba46bd61bd88526d93e029'

$ sudo make all
PACKAGE = metamorphose2
DESTDIR =
PREFIX = /usr
remusr = 0
msgfmt_location =
OS = Linux
# make needed directories
install -d /usr/share/metamorphose2/;
install -d /usr/share/man/man1/
gzip -c9 manpage.1 > metamorphose2.1.gz
install -m 644 metamorphose2.1.gz /usr/share/man/man1/
# make sure all permissions are correct
chmod -R a+r *;
find . -type d ! -regex '.*/\..*' -exec chmod 755 {} \;
rm metamorphose2.1.gz
# copy program files and libraries
mkdir -p /usr/share/metamorphose2
cp -pR src/* /usr/share/metamorphose2/;
# install translation files
cd messages && make install
make[1]: Entering directory '/home/kevin/metamorphose2/messages'
building en_US/LC_MESSAGES/metamorphose2.mo
/bin/sh: 5: -o: not found
building es/LC_MESSAGES/metamorphose2.mo
/bin/sh: 5: -o: not found
building fr/LC_MESSAGES/metamorphose2.mo
/bin/sh: 5: -o: not found
copying to /usr/share/locale/en_US/LC_MESSAGES/metamorphose2.mo
copying to /usr/share/locale/es/LC_MESSAGES/metamorphose2.mo
copying to /usr/share/locale/fr/LC_MESSAGES/metamorphose2.mo
deleting en_US/LC_MESSAGES/metamorphose2.mo
deleting es/LC_MESSAGES/metamorphose2.mo
deleting fr/LC_MESSAGES/metamorphose2.mo
make[1]: Leaving directory '/home/kevin/metamorphose2/messages'
# adjust app.py translations' search-path
sed -i "s|/usr|/usr|g" /usr/share/metamorphose2/app.py;
# install the executables
install -d /usr/bin/;
install -m 755 metamorphose2 /usr/bin/;
# adjust executable' path
sed -i "s|/usr|/usr|g" /usr/bin/metamorphose2;
# copy icon and launcher if folders exist
#must create this folders or rpm won't build
install -d /usr/share/pixmaps
install -m 644 src/icons/metamorphose64.png /usr/share/pixmaps/metamorphose2.png;\
if [ -d /usr/share/app-install/icons ]; then\
	ln -s /usr/share/pixmaps/metamorphose2.png /usr/share/app-install/icons/metamorphose2.png;\
fi;
install -d /usr/share/applications
install -m 644 metamorphose2.desktop /usr/share/applications/
# adjust launcher's path
sed -i "s|/usr|/usr|g" /usr/share/applications/metamorphose2.desktop
if [ -d /usr/share/app-install/desktop ]; then\
	ln -s /usr/share/applications/metamorphose2.desktop /usr/share/app-install/desktop/metamorphose2.desktop;\
fi;

$ cd ~
$ metamorphose2
python3: can't open file 'src/metamorphose2.py': [Errno 2] No such file or directory

change PREFIX=/usrx to PREFIX=/usr in /usr/bin/metamorphose2

$ metamorphose2 # (On first run, allows setting language and writes to ~/.metamorphose2 config dir... then:)
12:58:18: Debug: Adding duplicate image handler for 'Windows bitmap file'
Traceback (most recent call last):
  File "/usr/share/metamorphose2/metamorphose2.py", line 169, in OnInit
    self.main = MainWindow.create(None, cli_options)
  File "/usr/share/metamorphose2/MainWindow/__init__.py", line 45, in create
    return MainWindow(parent, options)
  File "/usr/share/metamorphose2/MainWindow/__init__.py", line 569, in __init__
    self.__init_ctrls(prnt)
  File "/usr/share/metamorphose2/MainWindow/__init__.py", line 406, in __init_ctrls
    self.bottomWindow = bottomWindow.MainPanel(self.splitter, self)
  File "/usr/share/metamorphose2/MainWindow/bottomWindow.py", line 284, in __init__
    self.__init_ctrls(prnt)
  File "/usr/share/metamorphose2/MainWindow/bottomWindow.py", line 236, in __init_ctrls
    self.display = ListCtrl(self, -1, size=wx.Size(520, -1))
  File "/usr/share/metamorphose2/MainWindow/bottomWindow.py", line 53, in __init__
    self.set_preferences()
  File "/usr/share/metamorphose2/MainWindow/bottomWindow.py", line 57, in set_preferences
    self.green = wx.ItemAttr()
AttributeError: module 'wx' has no attribute 'ItemAttr'
OnInit returned false, exiting...

Any help appreciated.

**Comment by timinaust** [comment]
Hi,
It looks like this is an issue between wxpython4.0 and wxpython4.1 where they are changing the name.

https://docs.wxpython.org/wx.ItemAttr.html
New in version 4.1/wxWidgets-3.1.1: (previous versions had a similar ListItemAttr class)

If you are able to test by editing "/usr/share/metamorphose2/MainWindow/bottomWindow.py" and replace ItemAttr() with ListItemAttr() four times between lines 57 and 63 I think that should fix it.  

If that works, I will update code accordingly.

**Comment by kevin201** [comment]
Hello,

Many thanks. I've just gone through the installation again, and see that you've already updated the amendments. All working fine now! Brilliant work, thank you so much!

I have my favourite renamer back now.

**Comment by timinaust** [comment]
Great to hear that...
