### ISSUE TITLE
Might need to define dependancies better

### ISSUE THREAD

**Issue by Melechtna** [timinaust/metamorphose2#7]
Gentoo

`
Traceback (most recent call last):
  File "/usr/share/metamorphose2/metamorphose2.py", line 51, in <module>
    instwxversion = list(map(int, wx.__version__.split(".")))[0]
ValueError: invalid literal for int() with base 10: 'post2'
`
not sure what python needs to run this, as there are several libraries that this could be referencing.

**Comment by timinaust** [comment]
Hi, this is looking for the version of wxpython that is installed.  

It looks like you have installed wxpython from a tagged version from 13 Nov 2019 which reports wx.__version__ as '4.0.7.post2'.

This version should be OK, it is just that the version number format is not the expected '4.0.7', which is causing the error.

I will update the source, but in the mean time you should be able to edit /usr/share/metamorphose2/metamorphose2.py and change line 51 from ...
```
instwxversion = list(map(int, wx.__version__.split(".")))[0]
```
to 
```
instwxversion = list(map(int, wx.__version__.split(".")[0:3]))[0]
```
Tim

**Comment by Melechtna** [comment]
I completely forgot about this, I've since switched off Gentoo and am using Nobara (a fedora fork/spin), so I should be fine now, but thank you.
